import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Split the Diff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Split the Diff
        </h1>

        <p className={styles.description}>
          Just here to help
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Total One</h2>
            <p>$10.00</p>
          </div>

          <div className={styles.card}>
            <h2>Total Two</h2>
            <p>$20.00</p>
          </div>

          <div className={styles.card}>
            <h2>Split the Diff!</h2>
            <p>1 &rarr; 2 $5</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
