import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  //declare state variables
  const [totalOne, setTotalOne] = useState(10)
  const [totalTwo, setTotalTwo] = useState(20)

  //declare event handlers
  const handleTotalOneChange = (e) => setTotalOne(e.target.value)
  const handleTotalTwoChange = (e) => setTotalTwo(e.target.value)

  return (
    <div className={styles.container}>
      <Head>
        <title>Split the Diff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Split the Diff
        </h1>

        <p className={styles.description}>
          Just here to help
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Total One</h2>
            <p>
              $<input 
                type="text" 
                id="total-one" 
                defaultValue={totalOne}
                value={totalOne}
                onChange={handleTotalOneChange} /> 
            </p>
          </div>

          <div className={styles.card}>
            <h2>Total Two</h2>
            <p>
              $<input 
              type="text" 
              id="total-two" 
              defualtValue={totalTwo} 
              value={totalTwo}
              onChange={handleTotalTwoChange} /> 
            </p>
          </div>

          <div className={styles.card}>
            <h2>Split the Diff!</h2>
            {totalOne < totalTwo ?
              <>
                <p>
                  1 &rarr; 2
                  <br />
                  ${(totalTwo - totalOne) / 2}
                </p>
              </> 
              :
              <>
                <p>
                  1 &larr; 2
                  <br />
                  ${(totalOne - totalTwo) / 2}
                </p>
              </>}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
